# 网站配置

# 导入主题
theme: jekyll-theme-chirpy

# 网页的语言 › http://www.lingoes.net/en/translator/langcode.htm
# 如果它与 `_data/locales` 文件夹中的某个文件名相同，布局语言也会更改，
# 否则，布局语言将使用默认值 'en'。
lang: zh-CN

# 设置时区 › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# jekyll-seo-tag 设置 › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: "囧囧JOJO - 博客" # 主标题

tagline:

description: docs
  # 用于 SEO meta 和 atom feed
# 一个简约、响应式、功能丰富的 Jekyll 主题，适合技术写作。

# 填写您的网站协议和主机名。
# 例如：'https://username.github.io'，请注意，结尾不要加 '/'。
url: "https://jiongjiongjojo.github.io"

github:
    username: jiongjiongJOJO # 更改为您的 GitHub 用户名

social:
    # 更改为您的全名。
    # 它将作为文章的默认作者以及页脚中的版权拥有者显示
    name: "囧囧JOJO"
    email: 41473909@qq.com  # 更改为您的电子邮件地址
    links:
        - https://t.me/jiongjiong_JOJO

# 网站验证设置
webmaster_verifications:
    google: Jlu_rpouiLgWcn__7UxlVla4D8kqvDotL3Ti_lO5q1U
    bing: # 填写您的 Bing 验证代码
    alexa: # 填写您的 Alexa 验证代码
    yandex: # 填写您的 Yandex 验证代码
    baidu: codeva-jTNqPCeMXp
    facebook: # 填写您的 Facebook 验证代码

# ↑ --------------------------
# 结束 jekyll-seo-tag 设置

# 网站分析设置
analytics:
    google:
        id: G-48JS2F3YB9
    goatcounter:
        id: # 填写您的 GoatCounter ID
    umami:
        id: # 填写您的 Umami ID
        domain: # 填写您的 Umami 域名
    matomo:
        id: # 填写您的 Matomo ID
        domain: # 填写您的 Matomo 域名
    cloudflare:
        id: # 填写您的 Cloudflare Web Analytics token

# 页面浏览量设置
pageviews:
    provider: # 当前仅支持 'goatcounter'

# 优先颜色模式设置。
#
# 注意：保持空白将默认跟随系统首选颜色，
# 并且在侧边栏的左下角将有一个切换按钮，允许用户切换深色和浅色主题。
#
# 可用选项：
#
#     light  - 使用浅色主题
#     dark   - 使用深色主题
#
theme_mode: # [light | dark]

# 媒体资源的 CDN 端点。
# 注意，一旦指定，CDN URL 将会添加到所有媒体资源（网站头像、文章图片、音频和视频文件）路径中，
# 以 '/' 开头的路径都会使用 CDN。
#
# 例如：'https://cdn.com'
cdn:

# 侧边栏的头像，支持本地或 CORS 资源
avatar: "/assets/images/favicons/favicon.png"

# 网站范围的社交预览图片 URL，用于 SEO `og:image` meta 标签。
# 它可以被每个页面的自定义 `page.image` 覆盖。
social_preview_image: # 字符串，本地或 CORS 资源

# 布尔类型，全局开启文章目录（TOC）功能。
toc: true

comments:
    # 全局切换文章评论系统。保持为空表示禁用。
    provider: disqus  # [disqus | utterances | giscus]
    # 提供商选项如下：
    disqus:
        shortname: jojo-blog  # 填写 Disqus 的 shortname › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
    # utterances 设置 › https://utteranc.es/
    utterances:
        repo: # <gh-username>/<repo>
        issue_term: # < url | pathname | title | ...>
    # Giscus 设置 › https://giscus.app
    giscus:
        repo: # <gh-username>/<repo>
        repo_id:
        category:
        category_id:
        mapping: # 可选，默认为 'pathname'
        strict: # 可选，默认为 '0'
        input_position: # 可选，默认为 'bottom'
        lang: # 可选，默认为 `site.lang` 的值
        reactions_enabled: # 可选，默认为 '1'

# 自托管静态资源， 可选 › https://github.com/cotes2020/chirpy-static-assets
assets:
    self_host:
        enabled: true  # 布尔类型，保持为空表示 false
        # 指定 Jekyll 环境，空表示两者都可用
        # 只有在 `assets.self_host.enabled` 为 'true' 时才有效
        env: # [development | production]

pwa:
    enabled: true # 启用 PWA 功能（可安装）
    cache:
        enabled: true # 启用 PWA 离线缓存
        # 这里定义的路径将会被排除在 PWA 缓存之外。
        # 通常其值是另一个网站的 `baseurl`，该网站与当前网站共享相同的域名。
        deny_paths:
        # - "/example"  # 该 URL 会匹配 `<SITE_URL>/example/*` 并且不会被 PWA 缓存

paginate: 10

# 您网站的基本 URL
baseurl: ""

# ------------ 以下选项不建议修改 ------------------

kramdown:
    footnote_backlink: "&#8617;&#xfe0e;"
    syntax_highlighter: rouge
    syntax_highlighter_opts: # Rouge 配置 › https://github.com/jneen/rouge#full-options
        css_class: highlight
        # default_lang: console
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

collections:
    tabs:
        output: true
        sort_by: order

defaults:
    - scope:
          path: "" # 空字符串表示项目中的所有文件
          type: posts
      values:
          layout: post
          comments: true # 启用文章评论。
          toc: true # 显示文章目录（TOC）。
          author: "囧囧JOJO"
          # 请勿修改以下参数，除非您自信能更新项目中所有其他文章链接的代码。
          permalink: /posts/:title/
    - scope:
          path: _drafts
      values:
          comments: false
    - scope:
          path: ""
          type: tabs # 请参见 `site.collections`
      values:
          layout: page
          permalink: /:title/
    - scope:
          path: assets/js/dist
      values:
          swcache: true

sass:
    style: compressed

compress_html:
    clippings: all
    comments: all
    endings: all
    profile: false
    blanklines: false
    ignore:
        envs: [development]

plugins:
    - jekyll-toc

exclude:
    - "*.gem"
    - "*.gemspec"
    - docs
    - tools
    - README.md
    - LICENSE
    - "*.config.js"
    - package*.json

include:
    - assets/images
    - googlef72a262a9d619322.html

jekyll-archives:
    enabled: [categories, tags]
    layouts:
        category: category
        tag: tag
    permalinks:
        tag: /tags/:name/
        category: /categories/:name/
